[package]
name = "my_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bytes = "1"
num_enum = "0.5.7"
log4rs = "1.0.0"
log = "0.4.14"
thiserror = "1.0.30"